### ISSUE TITLE
Long-term home in github.com/cloud-gov?

### ISSUE THREAD

**Issue by pburkholder** [GSA-TTS/cg-egress-proxy#4]
Would it make sense to migrate this to the cloud-gov org?

**Comment by mogul** [comment]
Only if the cloud.gov team has someone in it prepared to maintain and support it. Like, say, someone (re-)joining at the end of this month. ;)

**Comment by mogul** [comment]
We've since moved this to the `GSA-TTS` organization, which seems like a reasonable place for it given that this is essentially a customer-deployed bit of sample code rather than anything that the cloud.gov team itself uses/recommends.
